### ISSUE TITLE
How to customize?

### ISSUE THREAD

**Issue by reddyisavinash** [klinker41/android-chips#32]
Hello, I have been debugging the code since a day to replica as a android default messenger application but didn't get through the exact path. Could you please help me out to show the contact details on a recycler view under the AutoCompleteTextView instead of adding them to the ACTV as a dropdown list. TIA.

**Comment by KtodaZ** [comment]
Hello, 

How I would probably do this is to use [Cursor Loaders](https://developer.android.com/guide/components/loaders.html) to load the contact list and display them in a listView. You could customize it to look like the messenger app. Then if you wanted an easy way to do the chips you could use submitItem(name, uri).
I don't know if there's a way to do this without using your own code as you would most likely have to modify this library otherwise.
Good luck.

**Comment by klinker24** [comment]
Sorry this isn't something the library will do, definitely a custom implementation. You should look at the [ContactsContract](https://developer.android.com/reference/android/provider/ContactsContract.html) for information on how to read from the contacts `ContentProvider`.
